Leaner (less reliable) relay+para chains setup
ComposableFi/centauri pull request #111
Opened 2022-11-09 09:22 UTC by blasrodri

Requested by informal, to have something that can run on every machine. Running 3 nodes for the relay chain, and only one collator per parachain.

To test:

```sh
scripts/build-lean-setup.sh
scripts/run-lean-setup.sh
```

2022-11-09 14:45 UTC, blasrodri commented
I've asked Farhad to give this a go, to ensure that we're meeting his HW requirements.

2022-11-14 17:14 UTC, scglenn approved these changes

2022-11-23 21:02 UTC, Wizdave97 requested changes

2022-11-23 21:02 UTC, Wizdave97 commented on scripts/parachain-launch/config-lean.yml
> +      - --force-authoring
parachains need `--enable-offchain-indexing=true` flag

2022-11-23 22:44 UTC, blasrodri commented on scripts/parachain-launch/config-lean.yml
> +      - --force-authoring
added

2022-11-24 08:53 UTC, Wizdave97 approved these changes

2022-11-24 09:29 UTC, merged