pallet-ibc: add whitelisting
ComposableFi/centauri pull request #203
Opened 2023-02-10 14:33 UTC by blasrodri

This feature is useful while testing the DOT<>KSM bridge
on our parachains. Will likely be removed

2023-02-13 11:15 UTC, Wizdave97 reviewed
The whitelist should be used in the `transfer` extrinsic.

2023-02-13 11:45 UTC, dzmitry-lahoda requested changes
please use Origin `ensure`

2023-02-13 12:06 UTC, blasrodri commented
> please use Origin `ensure`

where?

2023-02-13 12:12 UTC, blasrodri commented
@dzmitry-lahoda do you mean

```rs
		type Whitelist: Contains<<Self as frame_system::Config>::AccountId>
			+ EnsureOrigin<<Self as frame_system::Config>::RuntimeOrigin>;
```

2023-02-13 12:27 UTC, dzmitry-lahoda commented
yes. No Contains. Just Ensure. Set it to SignedOrRoot. Or just EnsureSigned

2023-02-13 12:27 UTC, dzmitry-lahoda commented
you do not need Contains.

2023-02-13 12:29 UTC, blasrodri commented
> you do not need Contains.

but if we want to create a white list mechanism, how does this work?

2023-02-13 12:37 UTC, dzmitry-lahoda commented
ensure is abstraction over contains. it can do contains. ensure is just contains for origins.

2023-02-13 12:37 UTC, dzmitry-lahoda commented
so just make ensure, and in dali will setup proper config.

2023-02-13 12:39 UTC, Wizdave97 commented
I think `Contains` is more appropriate in this case. The goal is to ensure the origin executing the transaction is part of a whitelisted set

2023-02-13 13:29 UTC, Wizdave97 commented
> I think `Contains` is more appropriate in this case. The goal is to ensure the origin executing the transaction is part of a whitelisted set

@dzmitry-lahoda  the goal is just to have a few accounts hardcoded in the runtime config that are allowed to use ibc transfers.

2023-02-13 13:36 UTC, blasrodri commented
@KaiserKarel what's your opinion here?

2023-02-13 15:16 UTC, KaiserKarel commented on utils/parachain-node/runtime/src/lib.rs
> +	type Whitelist = SimpleIBCWhiteList;
Can be the AllowAll type for dedup

2023-02-13 15:16 UTC, KaiserKarel submitted a review, later dismissed

2023-02-13 19:14 UTC, Wizdave97 approved these changes

2023-02-14 06:57 UTC, blasrodri commented
@dzmitry-lahoda can you please review it again?

2023-02-14 12:27 UTC, blasrodri commented on contracts/pallet-ibc/src/lib.rs
> +			}
I had to revert, because of compilation issues

2023-02-14 21:38 UTC, obsessed-cake approved these changes

2023-02-14 21:45 UTC, merged