pallet-ibc: report the asset_id on fee collection
ComposableFi/centauri pull request #333
Opened 2023-05-23 16:05 UTC by blasrodri

2023-05-23 16:06 UTC, RustNinja submitted a review, later dismissed

2023-05-23 17:22 UTC, kkast requested changes

2023-05-23 17:22 UTC, kkast commented on contracts/pallet-ibc/src/ics20_fee/mod.rs
> +				asset_id,
assset_id result

2023-05-23 17:22 UTC, kkast commented on contracts/pallet-ibc/src/ics20_fee/mod.rs
> +				asset_id,
should we even allow to go further if asset_id was an err. i think we should throw and error

2023-05-24 19:25 UTC, RustNinja approved these changes

2023-05-28 21:12 UTC, merged